name: BFEXEOPT Android

on:
  workflow_dispatch:

jobs:
  Build:
    name: ${{ matrix.name }}

    strategy:
      matrix:
        include:
          - name: BFEXEOPT Android ARM64
            os: macos-15
            buildArgs: "android -ONLY_ARM64"
            artifactName: BFEXEOPT Android ARM64
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"

          - name: BFEXEOPT Android ARMv7
            os: macos-15
            buildArgs: "android -ONLY_ARMV7"
            artifactName: BFEXEOPT Android ARMv7
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"

    uses: ./.github/workflows/build.yml

    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}
